on: [push]

jobs:
    build:
        name: GrumPHP on (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
                php-versions: ['7.4', '8.0' ]
        env:
            extensions: intl, mbstring
        steps:
            - uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: ${{ env.extensions }}
                  tools: composer:v2
            - name: Get Composer Cache Directory
              id: composercache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composercache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: ${{ runner.os }}-composer-
            - name: Install dependencies
              run: |
                  composer install --prefer-dist
                  npm install --prefix vendor/shopware/platform/src/Administration/Resources/app/administration
            - run: ./vendor/bin/grumphp run